export const COMPANY_INFO = {
  name: "Axis Packaging",
  tagline: "Premium Custom Packaging Solutions",
  phone: "+447727083773",
  email: "info@axispackaging.com",
  address: "123 Industrial Blvd, Manufacturing City, MC 12345",
  hours: "Mon-Fri: 8AM-6PM PST",
}

export const NAVIGATION_ITEMS = [
  { name: "Home", href: "/" },
  { name: "Products", href: "/products" },
  { name: "Industries", href: "/industries" },
  { name: "Sustainability", href: "/sustainability" },
  { name: "About", href: "/about" },
  { name: "Contact", href: "/contact" },
  { name: "MOQ", href: "/moq" },
]

export const PRODUCT_CATEGORIES = [
  {
    name: "Custom Folding Carton Boxes",
    description: "Durable folding cartons crafted from thin, flexible paperboard",
    icon: "📦",
    image: "/assets/packify-custom-boxes.png",
    slug: "folding-carton-boxes",
  },
  {
    name: "Premium Rigid Boxes",
    description: "Premium packaging crafted from thick durable chipboard",
    icon: "🎁",
    image: "/assets/packify-luxury-boxes.png",
    slug: "rigid-boxes",
  },
  {
    name: "Custom Box Inserts",
    description: "Keep small products safe with tailored, protective box inserts",
    icon: "📋",
    image: "/assets/packify-inserts.png",
    slug: "box-inserts",
  },
  {
    name: "Custom Reusable Bags",
    description: "Say goodbye to plastic, carry reusable bags proudly",
    icon: "👜",
    image: "/assets/packify-custom-boxes.png",
    slug: "reusable-bags",
  },
  {
    name: "Printed Mailer Bags",
    description: "Eco mailer bags for shipping clothing and small retail products",
    icon: "📮",
    image: "/assets/packify-mailers.png",
    slug: "mailer-bags",
  },
  {
    name: "Flexible Packaging Pouches",
    description: "Maintain food freshness and safety using resealable packaging pouches",
    icon: "🥡",
    image: "/assets/packify-food-containers.png",
    slug: "flexible-pouches",
  },
  {
    name: "Metal Tin Containers",
    description: "Searching for packaging that protects and stands out from competitors",
    icon: "🥫",
    image: "/assets/packify-custom-boxes.png",
    slug: "tin-containers",
  },
  {
    name: "Retail POP Displays",
    description: "Showcase products beautifully on counters and retail store floor areas",
    icon: "🏪",
    image: "/assets/packify-display-boxes.png",
    slug: "pop-displays",
  },
  {
    name: "Vinyl Stickers Labels",
    description: "Add custom flair to your products and packaging for impact",
    icon: "🏷️",
    image: "/assets/packify-custom-boxes.png",
    slug: "stickers-labels",
  },
  {
    name: "Printed Kraft Boxes",
    description: "Showcase your products stylishly with sustainable kraft packaging",
    icon: "🌱",
    image: "/assets/packify-eco-boxes.png",
    slug: "kraft-boxes",
  },
  {
    name: "Paper Shopping Bags",
    description: "Stylish eco-friendly paper bags",
    icon: "🛍️",
    image: "/assets/packify-retail-packaging.png",
    slug: "paper-bags",
  },
  {
    name: "Eco-friendly Packaging",
    description: "Sustainable alternatives to packaging",
    icon: "♻️",
    image: "/assets/packify-eco-friendly-packaging.png",
    slug: "eco-friendly",
  },
]

export const TRUST_INDICATORS = [
  { text: "10+ Years Experience", icon: "⭐" },
  { text: "ISO 9001 Certified", icon: "🏆" },
  { text: "24/7 Customer Support", icon: "📞" },
  { text: "Free Design Consultation", icon: "🎨" },
]

export const INDUSTRIES = [
  {
    name: "Apparel",
    description: "Pair your apparel with one-of-a-kind custom printed clothing boxes",
    icon: "👕",
    image: "/assets/packify-fashion-packaging.png",
    slug: "apparel",
  },
  {
    name: "Bakery & Cake",
    description: "Show off your baked good with personalized cake and bakery boxes",
    icon: "🍰",
    image: "/assets/packify-food-packaging.png",
    slug: "bakery-cake",
  },
  {
    name: "Beer & Liquor",
    description: "Premium packaging for alcoholic beverages",
    icon: "🍺",
    image: "/assets/packify-custom-boxes.png",
    slug: "beer-liquor",
  },
  {
    name: "Beverage",
    description: "Custom packaging for all types of beverages",
    icon: "🥤",
    image: "/assets/packify-food-containers.png",
    slug: "beverage",
  },
  {
    name: "Candle",
    description: "Elegant packaging for candle products",
    icon: "🕯️",
    image: "/assets/packify-custom-boxes.png",
    slug: "candle",
  },
  {
    name: "Candy & Sweets",
    description: "Sweet packaging solutions for confectionery",
    icon: "🍬",
    image: "/assets/packify-chocolate-packaging.png",
    slug: "candy-sweets",
  },
  {
    name: "Cannabis",
    description: "Custom-crafted tamper proof marijuana packaging",
    icon: "🌿",
    image: "/assets/packify-cannabis-packaging.png",
    slug: "cannabis",
  },
  {
    name: "Chocolate",
    description: "Premium custom chocolate boxes and packaging",
    icon: "🍫",
    image: "/assets/packify-chocolate-packaging.png",
    slug: "chocolate",
  },
  {
    name: "Coffee",
    description: "Packaging solutions for coffee products",
    icon: "☕",
    image: "/assets/packify-food-containers.png",
    slug: "coffee",
  },
  {
    name: "Cosmetics",
    description: "Custom printed cosmetic boxes and packaging",
    icon: "💄",
    image: "/assets/packify-cosmetics-packaging.png",
    slug: "cosmetics",
  },
  {
    name: "E-Commerce",
    description: "Packaging solutions for online businesses",
    icon: "🛒",
    image: "/assets/packify-shipping-boxes.png",
    slug: "ecommerce",
  },
  {
    name: "Electronics",
    description: "Protective packaging for electronic devices",
    icon: "📱",
    image: "/assets/packify-electronics-packaging.png",
    slug: "electronics",
  },
  {
    name: "Food",
    description: "Safe and compliant food packaging solutions",
    icon: "🍽️",
    image: "/assets/packify-food-packaging.png",
    slug: "food",
  },
  {
    name: "Gift",
    description: "Beautiful packaging for gift items",
    icon: "🎁",
    image: "/assets/packify-luxury-boxes.png",
    slug: "gift",
  },
  {
    name: "Jewelry",
    description: "Luxury packaging for jewelry and accessories",
    icon: "💍",
    image: "/assets/packify-luxury-boxes.png",
    slug: "jewelry",
  },
  {
    name: "Pets",
    description: "Packaging for pet products and supplies",
    icon: "🐾",
    image: "/assets/packify-custom-boxes.png",
    slug: "pets",
  },
  {
    name: "Pharmaceutical",
    description: "Compliant packaging for pharmaceutical products",
    icon: "💊",
    image: "/assets/packify-pharmaceutical.png",
    slug: "pharmaceutical",
  },
  {
    name: "Presentation",
    description: "Professional presentation packaging",
    icon: "📊",
    image: "/assets/packify-custom-boxes.png",
    slug: "presentation",
  },
  {
    name: "Restaurant",
    description: "Packaging for restaurant and food service",
    icon: "🍽️",
    image: "/assets/packify-food-packaging.png",
    slug: "restaurant",
  },
  {
    name: "Retail",
    description: "Eye-catching retail displays and packaging",
    icon: "🏪",
    image: "/assets/packify-retail-packaging.png",
    slug: "retail",
  },
  {
    name: "Shipping",
    description: "Secure shipping and mailer solutions",
    icon: "📦",
    image: "/assets/packify-shipping-boxes.png",
    slug: "shipping",
  },
  {
    name: "Soap",
    description: "Packaging for soap and personal care products",
    icon: "🧼",
    image: "/assets/packify-custom-boxes.png",
    slug: "soap",
  },
  {
    name: "Toy",
    description: "Fun and safe packaging for toys",
    icon: "🧸",
    image: "/assets/packify-custom-boxes.png",
    slug: "toy",
  },
  {
    name: "Tea",
    description: "Elegant packaging for tea products",
    icon: "🫖",
    image: "/assets/packify-food-containers.png",
    slug: "tea",
  },
  {
    name: "Wine",
    description: "Premium packaging for wine and spirits",
    icon: "🍷",
    image: "/assets/packify-custom-boxes.png",
    slug: "wine",
  },
]

export const CERTIFICATIONS = [
  "ISO 9001:2015",
  "FSC Certified",
  "FDA Approved Materials",
  "ROHS Compliant",
  "Recyclable Materials",
]
